// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface CloudspaceBid {
    bidName?: pulumi.Input<string>;
    wonCount?: pulumi.Input<number>;
}

export interface CloudspacePendingAllocation {
    bidName?: pulumi.Input<string>;
    count?: pulumi.Input<number>;
    serverClass?: pulumi.Input<string>;
}

export interface CloudspaceTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string>;
}

export interface GetRegionsFilter {
    /**
     * Name of the attribute on which this filter should be applied. The tags attribute is a special case where the name has to be specified as 'tags:<tag_key>'
     */
    name: string;
    /**
     * Set of values for the attribute, if any of the 'value' matches then the filter is considered to be matched
     */
    values: string[];
}

export interface GetRegionsFilterArgs {
    /**
     * Name of the attribute on which this filter should be applied. The tags attribute is a special case where the name has to be specified as 'tags:<tag_key>'
     */
    name: pulumi.Input<string>;
    /**
     * Set of values for the attribute, if any of the 'value' matches then the filter is considered to be matched
     */
    values: pulumi.Input<pulumi.Input<string>[]>;
}

export interface GetServerclassesFilter {
    /**
     * Name of the attribute on which this filter should be applied. The tags attribute is a special case where the name has to be specified as 'tags:<tag_key>'
     */
    name: string;
    /**
     * If any of the 'value' matches, then the filter is considered to be matched. For numeric attributes like resources.cpu, resources.memory, and others, the values also support comparator expressions like >8GB, <=4, etc.
     */
    values: string[];
}

export interface GetServerclassesFilterArgs {
    /**
     * Name of the attribute on which this filter should be applied. The tags attribute is a special case where the name has to be specified as 'tags:<tag_key>'
     */
    name: pulumi.Input<string>;
    /**
     * If any of the 'value' matches, then the filter is considered to be matched. For numeric attributes like resources.cpu, resources.memory, and others, the values also support comparator expressions like >8GB, <=4, etc.
     */
    values: pulumi.Input<pulumi.Input<string>[]>;
}

export interface GetSpotnodepoolTaint {
    /**
     * The taint effect (NoSchedule, PreferNoSchedule, or NoExecute)
     */
    effect: string;
    /**
     * The taint key to be applied
     */
    key: string;
    /**
     * The taint value
     */
    value?: string;
}

export interface GetSpotnodepoolTaintArgs {
    /**
     * The taint effect (NoSchedule, PreferNoSchedule, or NoExecute)
     */
    effect: pulumi.Input<string>;
    /**
     * The taint key to be applied
     */
    key: pulumi.Input<string>;
    /**
     * The taint value
     */
    value?: pulumi.Input<string>;
}

export interface OndemandnodepoolTaint {
    /**
     * The taint effect (NoSchedule, PreferNoSchedule, or NoExecute)
     */
    effect: pulumi.Input<string>;
    /**
     * The taint key to be applied
     */
    key: pulumi.Input<string>;
    /**
     * The taint value
     */
    value?: pulumi.Input<string>;
}

export interface SpotnodepoolAutoscaling {
    /**
     * The maximum number of nodes in the node pool.
     */
    maxNodes?: pulumi.Input<number>;
    /**
     * The minimum number of nodes in the node pool.
     */
    minNodes?: pulumi.Input<number>;
}

export interface SpotnodepoolTaint {
    /**
     * The taint effect (NoSchedule, PreferNoSchedule, or NoExecute)
     */
    effect: pulumi.Input<string>;
    /**
     * The taint key to be applied
     */
    key: pulumi.Input<string>;
    /**
     * The taint value
     */
    value?: pulumi.Input<string>;
}
