// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface CloudspaceBid {
    bidName: string;
    wonCount: number;
}

export interface CloudspacePendingAllocation {
    bidName: string;
    count: number;
    serverClass: string;
}

export interface CloudspaceTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
}

export interface GetCloudspaceBid {
    bidName: string;
    wonCount: number;
}

export interface GetCloudspacePendingAllocation {
    bidName: string;
    count: number;
    serverClass: string;
}

export interface GetKubeconfigKubeconfig {
    /**
     * Name of the cluster
     */
    cluster: string;
    exec: outputs.GetKubeconfigKubeconfigExec;
    /**
     * Kube api server api endpoint
     */
    host: string;
    /**
     * Insecure flag
     */
    insecure: boolean;
    /**
     * Name of the kubeconfig context
     */
    name: string;
    /**
     * Token of your service account
     */
    token: string;
    /**
     * Name of the user
     */
    username: string;
}

export interface GetKubeconfigKubeconfigExec {
    /**
     * API version
     */
    apiVersion: string;
    args: string[];
    /**
     * Command to execute
     */
    command: string;
    env: {[key: string]: string};
}

export interface GetRegionRegionProvider {
    /**
     * Actual infrastructure backing the region
     */
    providerType: string;
    /**
     * Name of the region
     */
    regionName: string;
}

export interface GetRegionsFilter {
    /**
     * Name of the attribute on which this filter should be applied. The tags attribute is a special case where the name has to be specified as 'tags:<tag_key>'
     */
    name: string;
    /**
     * Set of values for the attribute, if any of the 'value' matches then the filter is considered to be matched
     */
    values: string[];
}

export interface GetServerclassOnDemandPricing {
    /**
     * Describes the USD cost of this type of servers. If pricing is localized, this can be used as the base factor
     */
    cost: string;
    /**
     * Indicates the interval used for the pricing
     */
    interval: string;
}

export interface GetServerclassResources {
    cpu: string;
    memory: string;
}

export interface GetServerclassServerclassProvider {
    /**
     * Name of the flavor
     */
    flavorId: string;
    /**
     * Actual infrastructure backing the server class
     */
    providerType: string;
}

export interface GetServerclassStatus {
    /**
     * how many servers of this class are currently in use
     */
    available: number;
    /**
     * how many servers of this class are currently in use
     */
    capacity: number;
    /**
     * how many servers of this class are currently in use
     */
    lastAuction: number;
    /**
     * how many servers of this class are currently in use
     */
    reserved: number;
    spotPricing: outputs.GetServerclassStatusSpotPricing;
}

export interface GetServerclassStatusSpotPricing {
    hammerPricePerHour: string;
    marketPricePerHour: string;
}

export interface GetServerclassesFilter {
    /**
     * Name of the attribute on which this filter should be applied. The tags attribute is a special case where the name has to be specified as 'tags:<tag_key>'
     */
    name: string;
    /**
     * If any of the 'value' matches, then the filter is considered to be matched. For numeric attributes like resources.cpu, resources.memory, and others, the values also support comparator expressions like >8GB, <=4, etc.
     */
    values: string[];
}

export interface GetSpotnodepoolAutoscaling {
    /**
     * The maximum number of nodes in the node pool.
     */
    maxNodes: number;
    /**
     * The minimum number of nodes in the node pool.
     */
    minNodes: number;
}

export interface GetSpotnodepoolTaint {
    /**
     * The taint effect (NoSchedule, PreferNoSchedule, or NoExecute)
     */
    effect: string;
    /**
     * The taint key to be applied
     */
    key: string;
    /**
     * The taint value
     */
    value?: string;
}

export interface OndemandnodepoolTaint {
    /**
     * The taint effect (NoSchedule, PreferNoSchedule, or NoExecute)
     */
    effect: string;
    /**
     * The taint key to be applied
     */
    key: string;
    /**
     * The taint value
     */
    value?: string;
}

export interface SpotnodepoolAutoscaling {
    /**
     * The maximum number of nodes in the node pool.
     */
    maxNodes?: number;
    /**
     * The minimum number of nodes in the node pool.
     */
    minNodes?: number;
}

export interface SpotnodepoolTaint {
    /**
     * The taint effect (NoSchedule, PreferNoSchedule, or NoExecute)
     */
    effect: string;
    /**
     * The taint key to be applied
     */
    key: string;
    /**
     * The taint value
     */
    value?: string;
}

