// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Cloudspace extends pulumi.CustomResource {
    /**
     * Get an existing Cloudspace resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CloudspaceState, opts?: pulumi.CustomResourceOptions): Cloudspace {
        return new Cloudspace(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'spot:index/cloudspace:Cloudspace';

    /**
     * Returns true if the given object is an instance of Cloudspace.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Cloudspace {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Cloudspace.__pulumiType;
    }

    declare public /*out*/ readonly bids: pulumi.Output<outputs.CloudspaceBid[]>;
    /**
     * The name of the cloudspace.
     */
    declare public readonly cloudspaceName: pulumi.Output<string>;
    /**
     * Container Network Interface (CNI) to use. Supported values: calico, cilium, byocni
     */
    declare public readonly cni: pulumi.Output<string>;
    /**
     * Specifies the deployment type for the cloudspace (Only gen2 is allowed value).
     *
     * @deprecated Deprecated
     */
    declare public readonly deploymentType: pulumi.Output<string>;
    /**
     * The time when the cloudspace was first ready.
     */
    declare public /*out*/ readonly firstReadyTimestamp: pulumi.Output<string>;
    /**
     * High Availability Kubernetes (replicated control plane for redundancy). This is a critical feature for production workloads.
     */
    declare public readonly hacontrolPlane: pulumi.Output<boolean>;
    /**
     * Kubernetes version to deploy in the cloudspace. Supported values: 1.29.6, 1.30.10, 1.31.1
     */
    declare public readonly kubernetesVersion: pulumi.Output<string>;
    /**
     * The last time the cloudspace was updated.
     */
    declare public /*out*/ readonly lastUpdated: pulumi.Output<string>;
    /**
     * The name of the cloudspace.
     */
    declare public readonly name: pulumi.Output<string>;
    declare public /*out*/ readonly pendingAllocations: pulumi.Output<outputs.CloudspacePendingAllocation[]>;
    /**
     * Webhook URL for preemption notifications.
     */
    declare public readonly preemptionWebhook: pulumi.Output<string | undefined>;
    /**
     * The region where the cloudspace will be created.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * IDs of the spotnodepools associated with the cloudspace.
     */
    declare public /*out*/ readonly spotnodepoolIds: pulumi.Output<string[]>;
    declare public readonly timeouts: pulumi.Output<outputs.CloudspaceTimeouts | undefined>;
    /**
     * If true, waits until the cloudspace control plane is ready
     */
    declare public readonly waitUntilReady: pulumi.Output<boolean>;

    /**
     * Create a Cloudspace resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CloudspaceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CloudspaceArgs | CloudspaceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CloudspaceState | undefined;
            resourceInputs["bids"] = state?.bids;
            resourceInputs["cloudspaceName"] = state?.cloudspaceName;
            resourceInputs["cni"] = state?.cni;
            resourceInputs["deploymentType"] = state?.deploymentType;
            resourceInputs["firstReadyTimestamp"] = state?.firstReadyTimestamp;
            resourceInputs["hacontrolPlane"] = state?.hacontrolPlane;
            resourceInputs["kubernetesVersion"] = state?.kubernetesVersion;
            resourceInputs["lastUpdated"] = state?.lastUpdated;
            resourceInputs["name"] = state?.name;
            resourceInputs["pendingAllocations"] = state?.pendingAllocations;
            resourceInputs["preemptionWebhook"] = state?.preemptionWebhook;
            resourceInputs["region"] = state?.region;
            resourceInputs["spotnodepoolIds"] = state?.spotnodepoolIds;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["waitUntilReady"] = state?.waitUntilReady;
        } else {
            const args = argsOrState as CloudspaceArgs | undefined;
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            resourceInputs["cloudspaceName"] = args?.cloudspaceName;
            resourceInputs["cni"] = args?.cni;
            resourceInputs["deploymentType"] = args?.deploymentType;
            resourceInputs["hacontrolPlane"] = args?.hacontrolPlane;
            resourceInputs["kubernetesVersion"] = args?.kubernetesVersion;
            resourceInputs["name"] = args?.name;
            resourceInputs["preemptionWebhook"] = args?.preemptionWebhook;
            resourceInputs["region"] = args?.region;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["waitUntilReady"] = args?.waitUntilReady;
            resourceInputs["bids"] = undefined /*out*/;
            resourceInputs["firstReadyTimestamp"] = undefined /*out*/;
            resourceInputs["lastUpdated"] = undefined /*out*/;
            resourceInputs["pendingAllocations"] = undefined /*out*/;
            resourceInputs["spotnodepoolIds"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Cloudspace.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Cloudspace resources.
 */
export interface CloudspaceState {
    bids?: pulumi.Input<pulumi.Input<inputs.CloudspaceBid>[]>;
    /**
     * The name of the cloudspace.
     */
    cloudspaceName?: pulumi.Input<string>;
    /**
     * Container Network Interface (CNI) to use. Supported values: calico, cilium, byocni
     */
    cni?: pulumi.Input<string>;
    /**
     * Specifies the deployment type for the cloudspace (Only gen2 is allowed value).
     *
     * @deprecated Deprecated
     */
    deploymentType?: pulumi.Input<string>;
    /**
     * The time when the cloudspace was first ready.
     */
    firstReadyTimestamp?: pulumi.Input<string>;
    /**
     * High Availability Kubernetes (replicated control plane for redundancy). This is a critical feature for production workloads.
     */
    hacontrolPlane?: pulumi.Input<boolean>;
    /**
     * Kubernetes version to deploy in the cloudspace. Supported values: 1.29.6, 1.30.10, 1.31.1
     */
    kubernetesVersion?: pulumi.Input<string>;
    /**
     * The last time the cloudspace was updated.
     */
    lastUpdated?: pulumi.Input<string>;
    /**
     * The name of the cloudspace.
     */
    name?: pulumi.Input<string>;
    pendingAllocations?: pulumi.Input<pulumi.Input<inputs.CloudspacePendingAllocation>[]>;
    /**
     * Webhook URL for preemption notifications.
     */
    preemptionWebhook?: pulumi.Input<string>;
    /**
     * The region where the cloudspace will be created.
     */
    region?: pulumi.Input<string>;
    /**
     * IDs of the spotnodepools associated with the cloudspace.
     */
    spotnodepoolIds?: pulumi.Input<pulumi.Input<string>[]>;
    timeouts?: pulumi.Input<inputs.CloudspaceTimeouts>;
    /**
     * If true, waits until the cloudspace control plane is ready
     */
    waitUntilReady?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a Cloudspace resource.
 */
export interface CloudspaceArgs {
    /**
     * The name of the cloudspace.
     */
    cloudspaceName?: pulumi.Input<string>;
    /**
     * Container Network Interface (CNI) to use. Supported values: calico, cilium, byocni
     */
    cni?: pulumi.Input<string>;
    /**
     * Specifies the deployment type for the cloudspace (Only gen2 is allowed value).
     *
     * @deprecated Deprecated
     */
    deploymentType?: pulumi.Input<string>;
    /**
     * High Availability Kubernetes (replicated control plane for redundancy). This is a critical feature for production workloads.
     */
    hacontrolPlane?: pulumi.Input<boolean>;
    /**
     * Kubernetes version to deploy in the cloudspace. Supported values: 1.29.6, 1.30.10, 1.31.1
     */
    kubernetesVersion?: pulumi.Input<string>;
    /**
     * The name of the cloudspace.
     */
    name?: pulumi.Input<string>;
    /**
     * Webhook URL for preemption notifications.
     */
    preemptionWebhook?: pulumi.Input<string>;
    /**
     * The region where the cloudspace will be created.
     */
    region: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.CloudspaceTimeouts>;
    /**
     * If true, waits until the cloudspace control plane is ready
     */
    waitUntilReady?: pulumi.Input<boolean>;
}
