// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getCloudspace(args?: GetCloudspaceArgs, opts?: pulumi.InvokeOptions): Promise<GetCloudspaceResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spot:index/getCloudspace:getCloudspace", {
        "cloudspaceName": args.cloudspaceName,
        "id": args.id,
        "name": args.name,
        "preemptionWebhook": args.preemptionWebhook,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCloudspace.
 */
export interface GetCloudspaceArgs {
    /**
     * @deprecated Deprecated
     */
    cloudspaceName?: string;
    /**
     * @deprecated Deprecated
     */
    id?: string;
    name?: string;
    preemptionWebhook?: string;
}

/**
 * A collection of values returned by getCloudspace.
 */
export interface GetCloudspaceResult {
    readonly apiServerEndpoint: string;
    readonly bids: outputs.GetCloudspaceBid[];
    /**
     * @deprecated Deprecated
     */
    readonly cloudspaceName: string;
    readonly cni: string;
    readonly deploymentType: string;
    readonly firstReadyTimestamp: string;
    readonly hacontrolPlane: boolean;
    readonly health: string;
    /**
     * @deprecated Deprecated
     */
    readonly id: string;
    /**
     * @deprecated Deprecated
     */
    readonly kubeconfig: string;
    readonly kubernetesVersion: string;
    readonly name: string;
    readonly ondemandnodepoolIds: string[];
    readonly pendingAllocations: outputs.GetCloudspacePendingAllocation[];
    readonly phase: string;
    readonly preemptionWebhook?: string;
    readonly reason: string;
    readonly region: string;
    readonly spotnodepoolIds: string[];
    readonly token: string;
    readonly user: string;
}
export function getCloudspaceOutput(args?: GetCloudspaceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCloudspaceResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spot:index/getCloudspace:getCloudspace", {
        "cloudspaceName": args.cloudspaceName,
        "id": args.id,
        "name": args.name,
        "preemptionWebhook": args.preemptionWebhook,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCloudspace.
 */
export interface GetCloudspaceOutputArgs {
    /**
     * @deprecated Deprecated
     */
    cloudspaceName?: pulumi.Input<string>;
    /**
     * @deprecated Deprecated
     */
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    preemptionWebhook?: pulumi.Input<string>;
}
