// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getKubeconfig(args?: GetKubeconfigArgs, opts?: pulumi.InvokeOptions): Promise<GetKubeconfigResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spot:index/getKubeconfig:getKubeconfig", {
        "cloudspaceName": args.cloudspaceName,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getKubeconfig.
 */
export interface GetKubeconfigArgs {
    cloudspaceName?: string;
    /**
     * @deprecated Deprecated
     */
    id?: string;
}

/**
 * A collection of values returned by getKubeconfig.
 */
export interface GetKubeconfigResult {
    readonly cloudspaceName: string;
    /**
     * @deprecated Deprecated
     */
    readonly id: string;
    readonly kubeconfigs: outputs.GetKubeconfigKubeconfig[];
    readonly raw: string;
}
export function getKubeconfigOutput(args?: GetKubeconfigOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetKubeconfigResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spot:index/getKubeconfig:getKubeconfig", {
        "cloudspaceName": args.cloudspaceName,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getKubeconfig.
 */
export interface GetKubeconfigOutputArgs {
    cloudspaceName?: pulumi.Input<string>;
    /**
     * @deprecated Deprecated
     */
    id?: pulumi.Input<string>;
}
