// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getOndemandnodepool(opts?: pulumi.InvokeOptions): Promise<GetOndemandnodepoolResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spot:index/getOndemandnodepool:getOndemandnodepool", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getOndemandnodepool.
 */
export interface GetOndemandnodepoolResult {
    readonly id: string;
}
export function getOndemandnodepoolOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetOndemandnodepoolResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spot:index/getOndemandnodepool:getOndemandnodepool", {
    }, opts, utilities.getPackage());
}
