// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getServerclass(args: GetServerclassArgs, opts?: pulumi.InvokeOptions): Promise<GetServerclassResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spot:index/getServerclass:getServerclass", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getServerclass.
 */
export interface GetServerclassArgs {
    name: string;
}

/**
 * A collection of values returned by getServerclass.
 */
export interface GetServerclassResult {
    readonly availability: string;
    readonly category: string;
    readonly displayName: string;
    readonly flavorType: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly onDemandPricing: outputs.GetServerclassOnDemandPricing;
    readonly region: string;
    readonly resources: outputs.GetServerclassResources;
    readonly serverclassProvider: outputs.GetServerclassServerclassProvider;
    readonly status: outputs.GetServerclassStatus;
}
export function getServerclassOutput(args: GetServerclassOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetServerclassResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spot:index/getServerclass:getServerclass", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getServerclass.
 */
export interface GetServerclassOutputArgs {
    name: pulumi.Input<string>;
}
