// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSpotnodepool(args?: GetSpotnodepoolArgs, opts?: pulumi.InvokeOptions): Promise<GetSpotnodepoolResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spot:index/getSpotnodepool:getSpotnodepool", {
        "annotations": args.annotations,
        "id": args.id,
        "labels": args.labels,
        "name": args.name,
        "taints": args.taints,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSpotnodepool.
 */
export interface GetSpotnodepoolArgs {
    annotations?: {[key: string]: string};
    /**
     * @deprecated Deprecated
     */
    id?: string;
    labels?: {[key: string]: string};
    name?: string;
    taints?: inputs.GetSpotnodepoolTaint[];
}

/**
 * A collection of values returned by getSpotnodepool.
 */
export interface GetSpotnodepoolResult {
    readonly annotations?: {[key: string]: string};
    readonly autoscaling: outputs.GetSpotnodepoolAutoscaling;
    readonly bidPrice: number;
    readonly bidStatus: string;
    readonly cloudspaceName: string;
    readonly desiredServerCount: number;
    /**
     * @deprecated Deprecated
     */
    readonly id: string;
    readonly labels?: {[key: string]: string};
    readonly name: string;
    readonly serverClass: string;
    readonly taints?: outputs.GetSpotnodepoolTaint[];
    readonly wonCount: number;
}
export function getSpotnodepoolOutput(args?: GetSpotnodepoolOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSpotnodepoolResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spot:index/getSpotnodepool:getSpotnodepool", {
        "annotations": args.annotations,
        "id": args.id,
        "labels": args.labels,
        "name": args.name,
        "taints": args.taints,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSpotnodepool.
 */
export interface GetSpotnodepoolOutputArgs {
    annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * @deprecated Deprecated
     */
    id?: pulumi.Input<string>;
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    name?: pulumi.Input<string>;
    taints?: pulumi.Input<pulumi.Input<inputs.GetSpotnodepoolTaintArgs>[]>;
}
