// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getServerclasses(args?: GetServerclassesArgs, opts?: pulumi.InvokeOptions): Promise<GetServerclassesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spot:index/getServerclasses:getServerclasses", {
        "filters": args.filters,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getServerclasses.
 */
export interface GetServerclassesArgs {
    filters?: inputs.GetServerclassesFilter[];
    id?: string;
}

/**
 * A collection of values returned by getServerclasses.
 */
export interface GetServerclassesResult {
    readonly filters?: outputs.GetServerclassesFilter[];
    readonly id?: string;
    readonly names: string[];
}
export function getServerclassesOutput(args?: GetServerclassesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetServerclassesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("spot:index/getServerclasses:getServerclasses", {
        "filters": args.filters,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getServerclasses.
 */
export interface GetServerclassesOutputArgs {
    filters?: pulumi.Input<pulumi.Input<inputs.GetServerclassesFilterArgs>[]>;
    id?: pulumi.Input<string>;
}
