// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { CloudspaceArgs, CloudspaceState } from "./cloudspace";
export type Cloudspace = import("./cloudspace").Cloudspace;
export const Cloudspace: typeof import("./cloudspace").Cloudspace = null as any;
utilities.lazyLoad(exports, ["Cloudspace"], () => require("./cloudspace"));

export { GetCloudspaceArgs, GetCloudspaceResult, GetCloudspaceOutputArgs } from "./getCloudspace";
export const getCloudspace: typeof import("./getCloudspace").getCloudspace = null as any;
export const getCloudspaceOutput: typeof import("./getCloudspace").getCloudspaceOutput = null as any;
utilities.lazyLoad(exports, ["getCloudspace","getCloudspaceOutput"], () => require("./getCloudspace"));

export { GetKubeconfigArgs, GetKubeconfigResult, GetKubeconfigOutputArgs } from "./getKubeconfig";
export const getKubeconfig: typeof import("./getKubeconfig").getKubeconfig = null as any;
export const getKubeconfigOutput: typeof import("./getKubeconfig").getKubeconfigOutput = null as any;
utilities.lazyLoad(exports, ["getKubeconfig","getKubeconfigOutput"], () => require("./getKubeconfig"));

export { GetOndemandnodepoolResult } from "./getOndemandnodepool";
export const getOndemandnodepool: typeof import("./getOndemandnodepool").getOndemandnodepool = null as any;
export const getOndemandnodepoolOutput: typeof import("./getOndemandnodepool").getOndemandnodepoolOutput = null as any;
utilities.lazyLoad(exports, ["getOndemandnodepool","getOndemandnodepoolOutput"], () => require("./getOndemandnodepool"));

export { GetRegionArgs, GetRegionResult, GetRegionOutputArgs } from "./getRegion";
export const getRegion: typeof import("./getRegion").getRegion = null as any;
export const getRegionOutput: typeof import("./getRegion").getRegionOutput = null as any;
utilities.lazyLoad(exports, ["getRegion","getRegionOutput"], () => require("./getRegion"));

export { GetRegionsArgs, GetRegionsResult, GetRegionsOutputArgs } from "./getRegions";
export const getRegions: typeof import("./getRegions").getRegions = null as any;
export const getRegionsOutput: typeof import("./getRegions").getRegionsOutput = null as any;
utilities.lazyLoad(exports, ["getRegions","getRegionsOutput"], () => require("./getRegions"));

export { GetServerclassArgs, GetServerclassResult, GetServerclassOutputArgs } from "./getServerclass";
export const getServerclass: typeof import("./getServerclass").getServerclass = null as any;
export const getServerclassOutput: typeof import("./getServerclass").getServerclassOutput = null as any;
utilities.lazyLoad(exports, ["getServerclass","getServerclassOutput"], () => require("./getServerclass"));

export { GetServerclassesArgs, GetServerclassesResult, GetServerclassesOutputArgs } from "./getServerclasses";
export const getServerclasses: typeof import("./getServerclasses").getServerclasses = null as any;
export const getServerclassesOutput: typeof import("./getServerclasses").getServerclassesOutput = null as any;
utilities.lazyLoad(exports, ["getServerclasses","getServerclassesOutput"], () => require("./getServerclasses"));

export { GetSpotnodepoolArgs, GetSpotnodepoolResult, GetSpotnodepoolOutputArgs } from "./getSpotnodepool";
export const getSpotnodepool: typeof import("./getSpotnodepool").getSpotnodepool = null as any;
export const getSpotnodepoolOutput: typeof import("./getSpotnodepool").getSpotnodepoolOutput = null as any;
utilities.lazyLoad(exports, ["getSpotnodepool","getSpotnodepoolOutput"], () => require("./getSpotnodepool"));

export { OndemandnodepoolArgs, OndemandnodepoolState } from "./ondemandnodepool";
export type Ondemandnodepool = import("./ondemandnodepool").Ondemandnodepool;
export const Ondemandnodepool: typeof import("./ondemandnodepool").Ondemandnodepool = null as any;
utilities.lazyLoad(exports, ["Ondemandnodepool"], () => require("./ondemandnodepool"));

export * from "./provider";
import { Provider } from "./provider";

export { SpotnodepoolArgs, SpotnodepoolState } from "./spotnodepool";
export type Spotnodepool = import("./spotnodepool").Spotnodepool;
export const Spotnodepool: typeof import("./spotnodepool").Spotnodepool = null as any;
utilities.lazyLoad(exports, ["Spotnodepool"], () => require("./spotnodepool"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "spot:index/cloudspace:Cloudspace":
                return new Cloudspace(name, <any>undefined, { urn })
            case "spot:index/ondemandnodepool:Ondemandnodepool":
                return new Ondemandnodepool(name, <any>undefined, { urn })
            case "spot:index/spotnodepool:Spotnodepool":
                return new Spotnodepool(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("spot", "index/cloudspace", _module)
pulumi.runtime.registerResourceModule("spot", "index/ondemandnodepool", _module)
pulumi.runtime.registerResourceModule("spot", "index/spotnodepool", _module)
pulumi.runtime.registerResourcePackage("spot", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:spot") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
