// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Ondemandnodepool extends pulumi.CustomResource {
    /**
     * Get an existing Ondemandnodepool resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OndemandnodepoolState, opts?: pulumi.CustomResourceOptions): Ondemandnodepool {
        return new Ondemandnodepool(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'spot:index/ondemandnodepool:Ondemandnodepool';

    /**
     * Returns true if the given object is an instance of Ondemandnodepool.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Ondemandnodepool {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Ondemandnodepool.__pulumiType;
    }

    /**
     * Annotations to be applied to the nodes of the node pool
     */
    declare public readonly annotations: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * The name of the cloudspace.
     */
    declare public readonly cloudspaceName: pulumi.Output<string>;
    /**
     * The desired number of servers in the node pool.
     */
    declare public readonly desiredServerCount: pulumi.Output<number>;
    /**
     * Labels to be applied to the nodes of the node pool
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * The last time the ondemandnodepool was updated.
     */
    declare public /*out*/ readonly lastUpdated: pulumi.Output<string>;
    /**
     * The name of the ondemandnodepool.
     */
    declare public /*out*/ readonly name: pulumi.Output<string>;
    /**
     * Number of reserved on-demand nodes.
     */
    declare public /*out*/ readonly reservedCount: pulumi.Output<number>;
    /**
     * Status of the ondemandnodepool.
     */
    declare public /*out*/ readonly reservedStatus: pulumi.Output<string>;
    /**
     * The server class to be used for the node pool can be obtained from the serverclasses data source.
     */
    declare public readonly serverClass: pulumi.Output<string>;
    /**
     * Kubernetes taints to be applied to the nodes of the node pool
     */
    declare public readonly taints: pulumi.Output<outputs.OndemandnodepoolTaint[] | undefined>;

    /**
     * Create a Ondemandnodepool resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OndemandnodepoolArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OndemandnodepoolArgs | OndemandnodepoolState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OndemandnodepoolState | undefined;
            resourceInputs["annotations"] = state?.annotations;
            resourceInputs["cloudspaceName"] = state?.cloudspaceName;
            resourceInputs["desiredServerCount"] = state?.desiredServerCount;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["lastUpdated"] = state?.lastUpdated;
            resourceInputs["name"] = state?.name;
            resourceInputs["reservedCount"] = state?.reservedCount;
            resourceInputs["reservedStatus"] = state?.reservedStatus;
            resourceInputs["serverClass"] = state?.serverClass;
            resourceInputs["taints"] = state?.taints;
        } else {
            const args = argsOrState as OndemandnodepoolArgs | undefined;
            if (args?.cloudspaceName === undefined && !opts.urn) {
                throw new Error("Missing required property 'cloudspaceName'");
            }
            if (args?.desiredServerCount === undefined && !opts.urn) {
                throw new Error("Missing required property 'desiredServerCount'");
            }
            if (args?.serverClass === undefined && !opts.urn) {
                throw new Error("Missing required property 'serverClass'");
            }
            resourceInputs["annotations"] = args?.annotations;
            resourceInputs["cloudspaceName"] = args?.cloudspaceName;
            resourceInputs["desiredServerCount"] = args?.desiredServerCount;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["serverClass"] = args?.serverClass;
            resourceInputs["taints"] = args?.taints;
            resourceInputs["lastUpdated"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["reservedCount"] = undefined /*out*/;
            resourceInputs["reservedStatus"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Ondemandnodepool.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Ondemandnodepool resources.
 */
export interface OndemandnodepoolState {
    /**
     * Annotations to be applied to the nodes of the node pool
     */
    annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The name of the cloudspace.
     */
    cloudspaceName?: pulumi.Input<string>;
    /**
     * The desired number of servers in the node pool.
     */
    desiredServerCount?: pulumi.Input<number>;
    /**
     * Labels to be applied to the nodes of the node pool
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The last time the ondemandnodepool was updated.
     */
    lastUpdated?: pulumi.Input<string>;
    /**
     * The name of the ondemandnodepool.
     */
    name?: pulumi.Input<string>;
    /**
     * Number of reserved on-demand nodes.
     */
    reservedCount?: pulumi.Input<number>;
    /**
     * Status of the ondemandnodepool.
     */
    reservedStatus?: pulumi.Input<string>;
    /**
     * The server class to be used for the node pool can be obtained from the serverclasses data source.
     */
    serverClass?: pulumi.Input<string>;
    /**
     * Kubernetes taints to be applied to the nodes of the node pool
     */
    taints?: pulumi.Input<pulumi.Input<inputs.OndemandnodepoolTaint>[]>;
}

/**
 * The set of arguments for constructing a Ondemandnodepool resource.
 */
export interface OndemandnodepoolArgs {
    /**
     * Annotations to be applied to the nodes of the node pool
     */
    annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The name of the cloudspace.
     */
    cloudspaceName: pulumi.Input<string>;
    /**
     * The desired number of servers in the node pool.
     */
    desiredServerCount: pulumi.Input<number>;
    /**
     * Labels to be applied to the nodes of the node pool
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The server class to be used for the node pool can be obtained from the serverclasses data source.
     */
    serverClass: pulumi.Input<string>;
    /**
     * Kubernetes taints to be applied to the nodes of the node pool
     */
    taints?: pulumi.Input<pulumi.Input<inputs.OndemandnodepoolTaint>[]>;
}
