// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Spotnodepool extends pulumi.CustomResource {
    /**
     * Get an existing Spotnodepool resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SpotnodepoolState, opts?: pulumi.CustomResourceOptions): Spotnodepool {
        return new Spotnodepool(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'spot:index/spotnodepool:Spotnodepool';

    /**
     * Returns true if the given object is an instance of Spotnodepool.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Spotnodepool {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Spotnodepool.__pulumiType;
    }

    /**
     * Annotations to be applied to the nodes of the node pool
     */
    declare public readonly annotations: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Scales the nodes in a cluster based on usage. This block should be omitted to disable autoscaling.
     */
    declare public readonly autoscaling: pulumi.Output<outputs.SpotnodepoolAutoscaling | undefined>;
    /**
     * The bid price for the server in USD, rounded to three decimal places.
     */
    declare public readonly bidPrice: pulumi.Output<number>;
    /**
     * Status of the bid associated with this spotnodepool.
     */
    declare public /*out*/ readonly bidStatus: pulumi.Output<string>;
    /**
     * The name of the cloudspace.
     */
    declare public readonly cloudspaceName: pulumi.Output<string>;
    /**
     * The desired number of servers in the node pool. Should be removed if autoscaling is enabled.
     */
    declare public readonly desiredServerCount: pulumi.Output<number>;
    /**
     * Labels to be applied to the nodes of the node pool
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * The last time the spotnodepool was updated.
     */
    declare public /*out*/ readonly lastUpdated: pulumi.Output<string>;
    /**
     * The name of the spotnodepool.
     */
    declare public /*out*/ readonly name: pulumi.Output<string>;
    /**
     * The server class to be used for the node pool can be obtained from the serverclasses data source.
     */
    declare public readonly serverClass: pulumi.Output<string>;
    /**
     * Kubernetes taints to be applied to the nodes of the node pool
     */
    declare public readonly taints: pulumi.Output<outputs.SpotnodepoolTaint[] | undefined>;
    /**
     * Number of won bids.
     */
    declare public /*out*/ readonly wonCount: pulumi.Output<number>;

    /**
     * Create a Spotnodepool resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SpotnodepoolArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SpotnodepoolArgs | SpotnodepoolState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SpotnodepoolState | undefined;
            resourceInputs["annotations"] = state?.annotations;
            resourceInputs["autoscaling"] = state?.autoscaling;
            resourceInputs["bidPrice"] = state?.bidPrice;
            resourceInputs["bidStatus"] = state?.bidStatus;
            resourceInputs["cloudspaceName"] = state?.cloudspaceName;
            resourceInputs["desiredServerCount"] = state?.desiredServerCount;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["lastUpdated"] = state?.lastUpdated;
            resourceInputs["name"] = state?.name;
            resourceInputs["serverClass"] = state?.serverClass;
            resourceInputs["taints"] = state?.taints;
            resourceInputs["wonCount"] = state?.wonCount;
        } else {
            const args = argsOrState as SpotnodepoolArgs | undefined;
            if (args?.bidPrice === undefined && !opts.urn) {
                throw new Error("Missing required property 'bidPrice'");
            }
            if (args?.cloudspaceName === undefined && !opts.urn) {
                throw new Error("Missing required property 'cloudspaceName'");
            }
            if (args?.serverClass === undefined && !opts.urn) {
                throw new Error("Missing required property 'serverClass'");
            }
            resourceInputs["annotations"] = args?.annotations;
            resourceInputs["autoscaling"] = args?.autoscaling;
            resourceInputs["bidPrice"] = args?.bidPrice;
            resourceInputs["cloudspaceName"] = args?.cloudspaceName;
            resourceInputs["desiredServerCount"] = args?.desiredServerCount;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["serverClass"] = args?.serverClass;
            resourceInputs["taints"] = args?.taints;
            resourceInputs["bidStatus"] = undefined /*out*/;
            resourceInputs["lastUpdated"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["wonCount"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Spotnodepool.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Spotnodepool resources.
 */
export interface SpotnodepoolState {
    /**
     * Annotations to be applied to the nodes of the node pool
     */
    annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Scales the nodes in a cluster based on usage. This block should be omitted to disable autoscaling.
     */
    autoscaling?: pulumi.Input<inputs.SpotnodepoolAutoscaling>;
    /**
     * The bid price for the server in USD, rounded to three decimal places.
     */
    bidPrice?: pulumi.Input<number>;
    /**
     * Status of the bid associated with this spotnodepool.
     */
    bidStatus?: pulumi.Input<string>;
    /**
     * The name of the cloudspace.
     */
    cloudspaceName?: pulumi.Input<string>;
    /**
     * The desired number of servers in the node pool. Should be removed if autoscaling is enabled.
     */
    desiredServerCount?: pulumi.Input<number>;
    /**
     * Labels to be applied to the nodes of the node pool
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The last time the spotnodepool was updated.
     */
    lastUpdated?: pulumi.Input<string>;
    /**
     * The name of the spotnodepool.
     */
    name?: pulumi.Input<string>;
    /**
     * The server class to be used for the node pool can be obtained from the serverclasses data source.
     */
    serverClass?: pulumi.Input<string>;
    /**
     * Kubernetes taints to be applied to the nodes of the node pool
     */
    taints?: pulumi.Input<pulumi.Input<inputs.SpotnodepoolTaint>[]>;
    /**
     * Number of won bids.
     */
    wonCount?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Spotnodepool resource.
 */
export interface SpotnodepoolArgs {
    /**
     * Annotations to be applied to the nodes of the node pool
     */
    annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Scales the nodes in a cluster based on usage. This block should be omitted to disable autoscaling.
     */
    autoscaling?: pulumi.Input<inputs.SpotnodepoolAutoscaling>;
    /**
     * The bid price for the server in USD, rounded to three decimal places.
     */
    bidPrice: pulumi.Input<number>;
    /**
     * The name of the cloudspace.
     */
    cloudspaceName: pulumi.Input<string>;
    /**
     * The desired number of servers in the node pool. Should be removed if autoscaling is enabled.
     */
    desiredServerCount?: pulumi.Input<number>;
    /**
     * Labels to be applied to the nodes of the node pool
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The server class to be used for the node pool can be obtained from the serverclasses data source.
     */
    serverClass: pulumi.Input<string>;
    /**
     * Kubernetes taints to be applied to the nodes of the node pool
     */
    taints?: pulumi.Input<pulumi.Input<inputs.SpotnodepoolTaint>[]>;
}
